<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class WebauthnCredential extends Model
{
    use HasFactory;

    /**
     * The data type of the primary key.
     *
     * WebAuthn credentials use a UUID primary key, generated client-agnostic
     * server-side on creation (see booted()).
     *
     * @var string
     */
    protected $keyType = 'string';

    /**
     * Indicates if the model's ID is auto-incrementing.
     *
     * UUIDs are generated by the application, not the database.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * The attributes that are mass assignable.
     *
     * `id` is deliberately excluded: it is a random UUID assigned in the
     * `creating` event, never client-provided.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'user_id',
        'credential_id',
        'public_key',
        'device_label',
        'counter',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'counter' => 'integer',
        ];
    }

    /**
     * Perform model boot-time setup.
     *
     * Assigns a random UUID v4 to `id` when a new credential is created,
     * ensuring a unique primary key without trusting any client input.
     */
    protected static function booted(): void
    {
        static::creating(function (WebauthnCredential $credential): void {
            if (empty($credential->getKey())) {
                $credential->id = (string) Str::uuid();
            }
        });
    }

    /**
     * Get the user that owns this WebAuthn credential.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
